lang = {
    "en" : {
        "home-text" : "Home",
        "login-text" : "Please, log in to use this application.",
        "login-link" : "Log in",
        "logout-link" : "Log out",
        "language-text" : "Language",
        "save-button" : "Save",
        "new-link" : "Add new bookmark",
        "no-links" : "There aren't bookmarks yet, you can start addin one.",
        "new-link-name" : "Name",
        "new-link-url" : "URL",
        "not-logged-in" : "You must be logged in to do that action.",
        "forbidden-access" : "You can't access to this resource.",
        "duplicated-name" : "The name you entered is already in use. Please, choose another one.",
        "link-added" : "Bookmark added succesfully.",
        "link-modified" : "Bookmark modified succesfully.",
        "link-deleted" : "Bookmark deleted succesfully.",
        "search-text" : "search",
        "no-results" : "There are no results",
        "tags-text" : "Tags (separated by spaces)",
        "tags-menu" : "Tags",
        "no-tags" : "There aren't any tags yet."

    },
    "es" : {
        "home-text" : "Inicio",
        "login-text" : "Por favor, inicia sesión para usar esta aplicación.",
        "login-link" : "Iniciar sesión",
        "logout-link" : "Cerrar sesión",
        "language-text" : "Idioma",
        "save-button" : "Guardar",
        "new-link" : "Añadir nuevo marcador",
        "no-links" : "Todavía no hay marcadores, puedes empezar añadiendo uno.",
        "new-link-name" : "Nombre",
        "new-link-url" : "URL",
        "not-logged-in" : "Debes estar logueado para hacer esa acción",
        "forbidden-access" : "No puedes acceder a este recurso",
        "duplicated-name" : "El nombre introducido ya está en uso. Por favor, elige otro.",
        "link-added" : "Marcador añadido correctamente.",
        "link-modified" : "Marcador modificado correctamente.",
        "link-deleted" : "Marcador borrado correctamente.",
        "search-text" : "buscar",
        "no-results" : "No hay resultados",
        "tags-text" : "Etiquetas (separadas por espacios)",
        "tags-menu" : "Etiquetas",
        "no-tags" : "No hay etiquetas todavía."
    },
    "gl" : {
        "home-text" : "Inicio",
        "login-text" : "Por favor, inicia sesión para empregar esta aplicación.",
        "login-link" : "Iniciar sesión",
        "logout-link" : "Pechar sesión",
        "language-text" : "Idioma",
        "save-button" : "Gardar",
        "new-link" : "Engadir novo marcador",
        "no-links" : "Aínda non hai marcadores, podes comezar engadindo un.",
        "new-link-name" : "Nome",
        "new-link-url" : "URL",
        "not-logged-in" : "Debes estar logueado para facer esa acción",
        "forbidden-access" : "Non podes acceder a este recurso",
        "duplicated-name" : "O nome introducido xa está en uso. Por favor, elixe outro.",
        "link-added" : "Marcador engadido correctamente.",
        "link-modified" : "Marcador modificado correctamente.",
        "link-deleted" : "Marcador borrado correctamente.",
        "search-text" : "buscar",
        "no-results" : "Non hai resultados",
        "tags-text" : "Etiquetas (separadas por espacios)",
        "tags-menu" : "Etiquetas",
        "no-tags" : "Aínda non hai etiquetas."
    }
}